name: flutter_ws
description: A mobile Mediathek based on the MediathekView Web API.
version: 1.1.1+3

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: 3.10.1

dependencies:
  http: ^1.1.0
  path_provider: ^2.0.15
  sqflite: ^2.0.3+1
  uuid: ^4.1.0
  json_object_lite: ^4.0.1
  device_info_plus: ^11.4.0
  url_launcher: ^6.1.10
  logging: ^1.1.0
  synchronized: ^3.0.0+3
  flutter_downloader: ^1.10.5
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.1
  auto_size_text: ^3.0.0
  carousel_slider: ^5.0.0
  quiver: ^3.2.2
  #flutter_swiper : ^1.1.6
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.6.1
  chewie: ^1.5.0
  wakelock_plus: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.1.1
  intro_slider: ^3.0.0
  connectivity_plus: ^6.1.4
  video_thumbnail: ^0.5.5
  countly_flutter: ^25.4.0
  giffy_dialog: ^2.0.0
  filesize: ^2.0.1

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  path: ^1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  ios: true
  image_path: "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/img/ard.png
      - assets/img/orf.png
      - assets/img/zdf.png
      - assets/img/wdr.png
      - assets/img/arte.png
      - assets/img/ndr.png
      - assets/img/3sat.png
      - assets/img/swr.png
      - assets/img/br.png
      - assets/img/dw.png
      - assets/img/hr.png
      - assets/img/kika.png
      - assets/img/mdr.png
      - assets/img/phoenix.png
      - assets/img/rbb.png
      - assets/img/srf.png
      - assets/img/MediathekViewLoading.png
      - assets/intro/intro_slider_1.png
      - assets/intro/intro_slider_2.png
      - assets/launcher/ic_launcher.png
      - assets/cast/ic_cast0_white.png
      - assets/cast/ic_cast1_white.png
      - assets/cast/ic_cast2_white.png
      - assets/cast/ic_cast_connected_white.png
      - assets/cast/ic_cast_white.png

  fonts:
    - family: OldStandard
      fonts:
        - asset: assets/fonts/OldStandard-Regular.ttf
          weight: 600
        - asset: assets/fonts/OldStandard-Bold.ttf
          weight: 400

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
